[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GitStats"
version = "0.1.0"
description = "GitHub statistics, profile README image generator"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
